print("    ALEXANDER NEWTOWN       ")
print(" Bienvenido a la calculadora de la familia Hellsing")
print("=============================================")
print("Eliga la operacion que desea realizar (Elegir el número de la operacion): ")
print("1. Suma")
print("2. Resta")
print("3. Multiplicacion")
print("4. Division")
op = int(input("Ingrese la operacion que desea realizar: "))
n1 = float(input("Ingrese el primer numero: "))
n2 = float(input("Ingrese el segundo numero: "))
